version: '3.8'
services:
  php:
    build: .
    ports:
     - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./config:/var/www/config
    depends_on:
     - db


  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes_app
      TZ: Europe/Budapest
    ports:
      - "3306:3306"
